name = "one"
type = "webpack"
workers_dev = true
account_id = "26f610bd2c7c4a0760237882bdd64921"
zone_id = "2c080c8ada42d49266da64a8f031d379"
kv_namespaces = [
    { binding = "BUCKET", id = "7dd31768978741dfbb7ca3ae19291e95" }
]

[env.staging]
name = "one-staging"
